<?php

use Illuminate\Database\Seeder;
use App\CnCifrasNacionales;
use Illuminate\Support\Facades\DB;

class cn_cifras_nacionalsTableSeeder extends Seeder
{
    /**
     * Run the database seeds
     *
     * @return void
     */
    public function run()
    {
        DB::table('cn_cifras_nacionales')->delete();

        // Añadimos una entrada a esta tabla
        /*PIB según actividad económica (millones de USD)*/
        /*2007 */
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 7004,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 4017,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 5356,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 3932,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 4175,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 2784,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 3241,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 4059,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 3231,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 5970,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 1303,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 865,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 1241,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 586,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 374,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 149,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 223,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2007,'valor' => 2497,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        /*2008*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 8465,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 5394,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 6743,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 4727,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 4813,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 3529,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 3642,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 4417,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 3521,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 8928,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 1441,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 947,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 1425,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 633,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 441,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 201,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 283,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 2212,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2009*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 8677,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 5928,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 6524,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 5185,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 5572,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 4237,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 3727,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 4601,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 3548,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 5121,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 1714,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 1182,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 1554,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 542,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 386,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 276,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 240,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 3506,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        /*2010*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 9322,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 6501,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 7241,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 5750,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 6071,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4539,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4302,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4768,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 3700,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 7576,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 1948,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 1312,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 1682,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 754,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 401,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 335,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 298,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 3056,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2011*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 10338,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 8106,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 8400,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 5996,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 6702,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 5013,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 5046,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 5064,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 3696,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 10463,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 2300,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 1428,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 1812,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 928,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 488,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 333,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 421,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 2740,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2012*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 11110,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 9421,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 9031,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 6943,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 6559,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 5500,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 5712,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 5348,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 3843,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 11381,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 2754,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 1630,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 1910,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 1045,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 571,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 334,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 462,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 4068,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2013*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 12408,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 10013,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 9977,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 7513,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 7231,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 6051,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 6550,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 5593,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 4300,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 11851,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 2591,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 1878,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 2021,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 1066,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 596,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 382,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 516,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 4596,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2014*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 14002,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 10891,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 10545,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 7833,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 8122,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 6682,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 7016,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 6008,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 4338,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 11267,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 3166,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 2054,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 2127,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 1253,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 599,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 429,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 563,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 4832,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2015*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 14321,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 11125,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 10218,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 8489,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 8406,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 6660,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 6887,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 6317,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 4773,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 4691,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 3165,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 2083,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 1984,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 1509,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 538,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 434,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 445,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 7248,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2016*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 14583,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 11871,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 9637,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 8692,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 8344,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6849,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6388,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6166,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 5139,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 3824,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 3094,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 2150,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 1972,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 1594,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 569,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 503,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 499,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6739,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        

         
    }
}
