<?php

use Illuminate\Database\Seeder;
use App\CnCifrasNacionales;
use Illuminate\Support\Facades\DB; 

class PibPorProvinciasMillonesUsdTableSeeder extends Seeder
{
    /**
     * Run the database seeds
     *
     * @return void
     */
    public function run()
    {
        //DB::table('cn_cifras_nacionales')->delete();

        // Añadimos una entrada a esta tabla
        /*PIB por Provincias (millones de USD)*/
        /*2007 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 12611,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 13215,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 2688,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 2373,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 1610,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 1485,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 1536,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 3358,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 1308,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 805,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 848,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 886,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 814,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 2635,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 492,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 330,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 279,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 454,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 180,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 308,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 134,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 162,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2007,'valor' => 2497,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2008 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 14131,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 14653,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3290,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 2740,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1938,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1862,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1752,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 4883,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1490,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 929,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 994,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 953,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1062,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 968,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3944,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1102,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 553,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 378,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 314,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 631,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 240,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 388,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 170,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 186,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 2212,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        
        /*2009 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 14420,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 15784,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 3393,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2915,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2125,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2053,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1896,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2944,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1644,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1049,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1029,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1065,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1176,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1037,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2429,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 1144,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 626,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 440,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 359,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 442,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 316,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 319,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 205,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 203,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 3506,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        /*2010 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 16327,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 17222,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3664,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3251,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2426,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2096,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1933,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3447,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1788,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1094,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1094,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1251,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1240,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1174,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 4251,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1084,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 640,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 469,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 365,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 750,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 313,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 239,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 205,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 176,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3056,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2011*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 18293,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 18355,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 4543,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 3728,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2705,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2511,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2143,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 6809,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2030,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1288,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1265,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1531,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1496,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1347,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 3471,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1042,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 807,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 527,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 416,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1135,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 374,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 294,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 247,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 182,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2740,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        /*2012*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 20686,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 20440,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 4880,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3945,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2746,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2857,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1789,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 8025,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2270,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1324,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1595,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1703,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1600,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1456,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3022,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1205,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 835,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 573,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 428,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 1043,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 386,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 303,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 256,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 188,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 4068,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2013*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 22957,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 22764,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5267,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 4223,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 2997,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 3036,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1977,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 8452,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 2375,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1420,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1587,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1751,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1686,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1524,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 3187,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1220,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 933,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 572,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 454,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1033,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 378,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 309,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 244,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 188,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 4596,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2014*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 25866,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 24750,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 5463,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 4433,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 3319,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 3331,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 2144,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 8367,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 2524,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1626,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1647,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1867,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1686,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1586,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 2756,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1284,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 939,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 637,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 483,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 982,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 406,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 333,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 257,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 207,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 4832,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


        /*2015*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 25313,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 24409,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 5600,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 4766,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 3556,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 3293,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 2519,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 3466,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 2757,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1859,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1800,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1877,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1838,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1731,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1811,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1254,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1025,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 685,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 555,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 613,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 453,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 368,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 290,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 207,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 7248,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2016*/
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 25270,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 24970,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 5963,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 4737,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 3508,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 3199,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 2930,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 2721,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 2630,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1950,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1824,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1787,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1773,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1674,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1604,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1140,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1020,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 661,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 576,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 546,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 453,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 422,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 290,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 225,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 6739,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 1,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
    }
}
