<?php

use Illuminate\Database\Seeder;
use App\CnCifrasNacionales;
use Illuminate\Support\Facades\DB;

class PibPorProvinciasContribucionVariacionAnualTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	//DB::table('cn_cifras_nacionales')->delete();

        // Añadimos una entrada a esta tabla
        /*PIB por Provincias (Contribucion Variacion Anual)*/
        /*2007 NO Tiene Registros*/
        /*2008*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

                /*2009*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


                /*2010*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


                /*2011*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));


                /*2012*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

                /*2013*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

         /*2014*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

         /*2015*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

         /*2016*/

        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 4,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

    }
}
