<?php

use Illuminate\Database\Seeder;
use App\CnCifrasNacionales;
use Illuminate\Support\Facades\DB;

class PibPorProvinciasVariacionAnunalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('cn_cifras_nacionales')->delete();

        // Añadimos una entrada a esta tabla
        /*PIB por Provincias (variaciòn anual)*/
        /*2007 No tiene Registro*/
       
        /*2008 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 22,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 25,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 45,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 19,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 50,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 39,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 33,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 26,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 27,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2008,'valor' => -11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2009 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -40,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -38,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -30,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 32,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => -18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2009,'valor' => 59,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2010 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 75,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 70,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -25,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2010,'valor' => -13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2011 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 24,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 98,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 22,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => -18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => -4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 26,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 51,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 23,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2011,'valor' => -10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2012 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => -17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 26,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => -13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => -8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2012,'valor' => 48,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2013 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2013,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2014 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => -14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2015 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -59,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -34,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => -38,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2015,'valor' => 50,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2016 */
        
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 19,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 10,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 14,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 1,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 13,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 7,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 8,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 17,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 23,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 5,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 21,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 11,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 12,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 6,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 22,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 20,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 3,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 4,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 2,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 18,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 15,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 16,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 24,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 9,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB por provincias','año' => 2016,'valor' => -7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 28,'ciiu_id' => 188,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

    } 
}
