<?php

use Illuminate\Database\Seeder;
use App\CnCifrasNacionales;
use Illuminate\Support\Facades\DB;

class PibSegunActividadEconomicaVariacionAnualTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('cn_cifras_nacionales')->delete();

        // Añadimos una entrada a esta tabla
        /*PIB según actividad económica (variación anual)*/
        /*2007 no tiene Registros*/
        /*2008*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 34,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 26,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 27,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 50,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 35,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 27,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2008,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2009*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => -43,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 19,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 25,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => -14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => -13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 37,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2009,'valor' => 59,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2010*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 48,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 39,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => 24,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2010,'valor' => -13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2011*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 11,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 25,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 38,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 23,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 22,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => 41,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2011,'valor' => -10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2012*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 22));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 14,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 17,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 48,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2013*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => -6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2012,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 15,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2013,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2014*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 13,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 4,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => -5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 22,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 9,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2014,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2015*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 5,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -58,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 0,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 20,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -10,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => -21,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2015,'valor' => 50,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));

        /*2016*/
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 9,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 14,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 15,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 36,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 2,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 31,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 28,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 27,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 8,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 18,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -18,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 6,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -2,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 24,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 3,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 21,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -1,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 20,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 11,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 6,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 4,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 16,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 42,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => 12,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 3,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
        CnCifrasNacionales::create(array('nombre_cifra_nacional' => 'PIB según actividad económica','año' => 2016,'valor' => -7,'tipo_impuesto_id' => 16,'tipo_cifra_nacional_id' => 3,'tipo_empresa_id' => 7,'provincia_id' => 27,'ciiu_id' => 34,'tipo_fuente_id' => 1,'zona_id' => 13,'subsector_id' => 23));
    }
}
